from .api import list_instrument_ids, list_features, load_dataset, submit_feature
from .base import InstrumentIDRelated, InstrumentIDUnRelated, PersistentFeature, NonPersistentFeature
from .time import TimeRange

from .zoo.Close_Daily         import Close_Daily
from .zoo.Close_Min           import Close_Min
from .zoo.High_Daily          import High_Daily
from .zoo.High_Min            import High_Min
from .zoo.Low_Daily           import Low_Daily
from .zoo.Low_Min             import Low_Min
from .zoo.Money_Daily         import Money_Daily
from .zoo.Money_Min           import Money_Min
from .zoo.Open_Daily          import Open_Daily
from .zoo.Open_Min            import Open_Min
from .zoo.TurnOver_Daily      import TurnOver_Daily
from .zoo.TurnOver_Full_Daily import TurnOver_Full_Daily
from .zoo.Vol_Daily           import Vol_Daily
from .zoo.Vol_Min             import Vol_Min
from .zoo.Rate_Daily          import Rate_Daily
from .zoo.ChangeRate_Daily    import ChangeRate_Daily

# function
from .zoo.VR             import VR
from .zoo.TRIX           import TRIX
from .zoo.TRMA           import TRMA
from .zoo.RSI            import RSI
from .zoo.ROC            import ROC
from .zoo.EMV            import EMV
from .zoo.BOLL           import BOLL
from .zoo.OBV            import OBV
from .zoo.BBI            import BBI
from .zoo.TR             import TR
from .zoo.Sharpe         import Sharpe
from .zoo.PSY            import PSY
from .zoo.MFI            import MFI
from .zoo.CVAR           import CVAR
from .zoo.Aroon          import Aroon
from .zoo.WILLR          import WILLR
from .zoo.ADX            import ADX
from .zoo.CCI            import CCI
from .zoo.Alpha          import Alpha
from .zoo.Beta           import Beta
from .zoo.KDJ            import KDJ
from .zoo.DIFF           import DIFF
from .zoo.DEA            import DEA
from .zoo.MACD           import MACD

from .zoo.MA10_Daily     import MA10_Daily
from .zoo.MA20_Daily     import MA20_Daily
from .zoo.MA30_Daily     import MA30_Daily
from .zoo.MA5_Daily      import MA5_Daily
from .zoo.MA60_Daily     import MA60_Daily
from .zoo.EMA5_Daily     import EMA5_Daily
from .zoo.EMA10_Daily    import EMA10_Daily
from .zoo.EMA20_Daily    import EMA20_Daily
from .zoo.EMA30_Daily    import EMA30_Daily
from .zoo.EMA60_Daily    import EMA60_Daily
from .zoo.Std20_Daily    import Std20_Daily
from .zoo.EMA10_Daily    import EMA10_Daily
from .zoo.BIAS10_Daily   import BIAS10_Daily
from .zoo.BBI_Daily      import BBI_Daily
from .zoo.ROC_Daily      import ROC_Daily
from .zoo.OBV_Daily      import OBV_Daily
from .zoo.DIFF_Daily     import DIFF_Daily
from .zoo.DEA_Daily      import DEA_Daily
from .zoo.MACD_Daily     import MACD_Daily
from .zoo.EMV_Daily      import EMV_Daily
from .zoo.RSI6_Daily     import RSI6_Daily
from .zoo.CCI14_Daily    import CCI14_Daily
from .zoo.VR24_Daily     import VR24_Daily
from .zoo.TRIX_Daily     import TRIX_Daily
from .zoo.TRMA_Daily     import TRMA_Daily
from .zoo.TR_Daily       import TR_Daily
from .zoo.PSY_Daily      import PSY_Daily
from .zoo.MFI_Daily      import MFI_Daily
from .zoo.ADX_Daily      import ADX_Daily
from .zoo.KDJK_Daily    import KDJK_Daily
from .zoo.KDJD_Daily    import KDJD_Daily
from .zoo.KDJJ_Daily    import KDJJ_Daily
from .zoo.BOLLUp_Daily   import BOLLUp_Daily
from .zoo.BOLLDown_Daily import BOLLDown_Daily
from .zoo.AroonUp_Daily  import AroonUp_Daily
from .zoo.ArronDown_Daily import AroonDown_Daily
from .zoo.WILLR_Daily    import WILLR_Daily
from .zoo.CVAR_normal_Daily     import CVAR_normal_Daily
from .zoo.Sharpe40_Daily import Sharpe40_Daily
from .zoo.AlphaHS300_Daily import AlphaHS300_Daily
from .zoo.BetaHS300_Daily  import BetaHS300_Daily


from .zoo.Snowball_deal import Snowball_deal
from .zoo.Snowball_deal_week import Snowball_deal_week
from .zoo.Snowball_follow import Snowball_follow
from .zoo.Snowball_follow_week import Snowball_follow_week
from .zoo.Snowball_tweet import Snowball_tweet
from .zoo.Snowball_tweet_week import Snowball_tweet_week

# Private
from .zoo.Leo1_Daily     import Leo1_Daily

from .zoo.revenue import Revenue
from .zoo.roi import Roi
from .zoo.operating_expenses import Operating_expenses
from .zoo.operating_profit import Operating_profit
from .zoo.subsidize_revenue import Subsidize_revenue
from .zoo.nonbusiness_income import Nonbusiness_income
from .zoo.nonbusiness_expenditure import Nonbusiness_expenditure
from .zoo.total_profit import Total_profit
from .zoo.net_profit import Net_profit
from .zoo.basic_eps import Basic_eps
from .zoo.diluted_eps import Diluted_eps
from .zoo.cash_inflows_from_operating_activities import Cash_inflows_from_operating_activities
from .zoo.cash_outflow_for_operating_activities import Cash_outflow_for_operating_activities
from .zoo.net_cash_flow_for_operating_activities import Net_cash_flow_for_operating_activities
from .zoo.cash_inflow_from_investment_activities import Cash_inflow_from_investment_activities
from .zoo.cash_outflow_for_investment_activities import Cash_outflow_for_investment_activities
from .zoo.net_cash_flow_for_investment_activities import Net_cash_flow_for_investment_activities
from .zoo.cash_inflow_from_financing_activities import Cash_inflow_from_financing_activities
from .zoo.cash_outflow_for_financing_activities import Cash_outflow_for_financing_activities
from .zoo.net_cash_flow_from_financing_activities import Net_cash_flow_from_financing_activities
from .zoo.beginning_balance_of_cash_and_cash_equivalents import Beginning_balance_of_cash_and_cash_equivalents
from .zoo.final_balance_of_cash_and_cash_equivalents import Final_balance_of_cash_and_cash_equivalents
from .zoo.total_assets import Total_assets
from .zoo.equity import Equity
from .zoo.rnavps import Rnavps
from .zoo.current_ratio import Current_ratio
from .zoo.quick_ratio import Quick_ratio
from .zoo.cash_ratio import Cash_ratio
from .zoo.equity_to_debt_ratio import Equity_to_debt_ratio
from .zoo.interest_coverage_ratio import Interest_coverage_ratio
from .zoo.gross_margin import Gross_margin
from .zoo.net_margin import Net_margin
from .zoo.operating_margin import Operating_margin
from .zoo.accounts_receivable_turnover_ratio import Accounts_receivable_turnover_ratio
from .zoo.inventory_turnover_ratio import Inventory_turnover_ratio
from .zoo.total_assets_turnover_ratio import Total_assets_turnover_ratio
from .zoo.net_asset_turnover_ratio import Net_asset_turnover_ratio
from .zoo.assets_liabilities_ratio import Assets_liabilities_ratio
from .zoo.right_coefficient import Right_coefficient
from .zoo.moig import Moig
from .zoo.net_profit_growth_rate import Net_profit_growth_rate
from .zoo.increasing_rate_of_eps import Increasing_rate_of_eps
from .zoo.nav import Nav
from .zoo.inventory import Inventory
from .zoo.fixed_assets import Fixed_assets
from .zoo.intangible_assets import Intangible_assets
from .zoo.deferred_income_tax_assets import Deferred_income_tax_assets
from .zoo.total_assets import Total_assets
from .zoo.accounts_payable import Accounts_payable
from .zoo.total_liabilities import Total_liabilities
from .zoo.paid_in_capital import Paid_in_capital
from .zoo.capital_reserves import Capital_reserves
from .zoo.total_owners_equity import Total_owners_equity
from .zoo.cost_of_sales import Cost_of_sales
from .zoo.administration_expense_cost import Administration_expense_cost
from .zoo.financial_expenses import Financial_expenses
from .zoo.operating_profit import Operating_profit
from .zoo.total_profit import Total_profit
from .zoo.net_profit import Net_profit
from .zoo.accounts_receivable import Accounts_receivable
from .zoo.total_current_assets import Total_current_assets
from .zoo.total_noncurrent_assets import Total_noncurrent_assets
from .zoo.accounts_payable import Accounts_payable
from .zoo.total_current_liability import Total_current_liability
from .zoo.total_noncurrent_liabilities import Total_noncurrent_liabilities

from .zoo.capital import Capital
from .zoo.bvps import Bvps
from .zoo.ocfps import Ocfps
from .zoo.orps import Orps
from .zoo.eps import Eps
from .zoo.gpr import Gpr
from .zoo.npr import Npr
from .zoo.roe import Roe
from .zoo.roa import Roa
from .zoo.lev import Lev
from .zoo.G_TotalOperatingRevenue import G_TotalOperatingRevenue
from .zoo.G_NetProfit import G_NetProfit

from .zoo.Turnover_At_AM10 import Turnover_At_AM10
from .zoo.Turnover_Full_At_AM10 import Turnover_Full_At_AM10

from .zoo.Rate import Rate
from .zoo.Shibor_overnight import Shibor_overnight
from .zoo.Shibor_1week import Shibor_1week
from .zoo.Shibor_1month import Shibor_1month

from .zoo.G_EPS import G_EPS
from .zoo.G_EPSCAGR5 import G_EPSCAGR5
from .zoo.G_NetAssetsPerShare import G_NetAssetsPerShare
from .zoo.G_NetCashFlow import G_NetCashFlow
from .zoo.G_NeToperateCashFlow import G_NeToperateCashFlow
from .zoo.G_NeToperateCashFlowPerShare import G_NeToperateCashFlowPerShare
from .zoo.G_NetProfit3YAvg import G_NetProfit3YAvg
from .zoo.G_NetProfitCAGR3 import G_NetProfitCAGR3
from .zoo.G_NetProfitCAGR5 import G_NetProfitCAGR5
from .zoo.G_OperatingProfit import G_OperatingProfit
from .zoo.G_OperatingRevenueCAGR3 import G_OperatingRevenueCAGR3
from .zoo.G_OperatingRevenueCAGR5 import G_OperatingRevenueCAGR5
from .zoo.G_ROE import G_ROE
from .zoo.G_TotalAssets import G_TotalAssets
from .zoo.G_TotalOperatingRevenue12QAvg import G_TotalOperatingRevenue12QAvg
from .zoo.G_TotalProfit import G_TotalProfit

from .zoo.CMO import CMO
from .zoo.CMO5 import CMO5
from .zoo.CMO10 import CMO10
from .zoo.CMO20 import CMO20

from .zoo.Neu_BP import Neu_BP
from .zoo.Neu_CF_P import Neu_CF_P
from .zoo.Neu_EBIT_P import Neu_EBIT_P
from .zoo.Neu_EP import Neu_EP
from .zoo.Neu_MV import Neu_MV
from .zoo.Neu_P_EBIT import Neu_P_EBIT
from .zoo.Neu_P_RE import Neu_P_RE
from .zoo.Neu_PB import Neu_PB
from .zoo.Neu_PCF import Neu_PCF
from .zoo.Neu_PE import Neu_PE
from .zoo.Neu_PS import Neu_PS
from .zoo.Neu_RE_P import Neu_RE_P
from .zoo.Neu_SP import Neu_SP

from .zoo.Neu_G_EPS import Neu_G_EPS
from .zoo.Neu_G_EPSCAGR5 import Neu_G_EPSCAGR5
from .zoo.Neu_G_NetAssetsPerShare import Neu_G_NetAssetsPerShare
from .zoo.Neu_G_NetCashFlow import Neu_G_NetCashFlow
from .zoo.Neu_G_NeToperateCashFlow import Neu_G_NeToperateCashFlow
from .zoo.Neu_G_NeToperateCashFlowPerShare import Neu_G_NeToperateCashFlowPerShare
from .zoo.Neu_G_NetProfit3YAvg import Neu_G_NetProfit3YAvg
from .zoo.Neu_G_NetProfitCAGR3 import Neu_G_NetProfitCAGR3
from .zoo.Neu_G_NetProfitCAGR5 import Neu_G_NetProfitCAGR5
from .zoo.Neu_G_OperatingProfit import Neu_G_OperatingProfit
from .zoo.Neu_G_OperatingRevenueCAGR3 import Neu_G_OperatingRevenueCAGR3
from .zoo.Neu_G_OperatingRevenueCAGR5 import Neu_G_OperatingRevenueCAGR5
from .zoo.Neu_G_ROE import Neu_G_ROE
from .zoo.Neu_G_TotalAssets import Neu_G_TotalAssets
from .zoo.Neu_G_TotalOperatingRevenue import Neu_G_TotalOperatingRevenue
from .zoo.Neu_G_TotalOperatingRevenue12QAvg import Neu_G_TotalOperatingRevenue12QAvg
from .zoo.Neu_G_TotalProfit import Neu_G_TotalProfit
from .zoo.ReferencePrice_Daily import ReferencePrice_Daily
from .zoo.CapitalGain_Daily import CapitalGain_Daily
from .zoo.Skewness_Daily import Skewness_Daily
from .zoo.Kurtosis_Daily import Kurtosis_Daily
from .zoo.Halflife_Kurtosis_Daily import Halflife_Kurtosis_Daily
from .zoo.AbnormalVolatility_Daily import AbnormalVolatility_Daily
from .zoo.Halflife_CVAR_Daily import Halflife_CVAR_Daily
from .zoo.Halflife_Std_Daily import Halflife_Std_Daily
from .zoo.Inv_Halflife_Std_Daily import Inv_Halflife_Std_Daily
from .zoo.Momentum_Daily import Momentum_Daily
from .zoo.Halflife_Momentum_Daily import Halflife_Momentum_Daily
