import pymongo
from mongoapi.config import *
GLOBAL_MONGO_CONN = pymongo.MongoClient(PORT, MONGODB_PORT)
DATA_DB = GLOBAL_MONGO_CONN[MONGODB_DB]
MINUTE_COLLECTION = DATA_DB[MONGODB_COLLECTION_MINUTE]
DAY_COLLECTION = DATA_DB[MONGODB_COLLECTION_DAY]

INDEX_DAY_COLLECTION = GLOBAL_MONGO_CONN['db_index']['IndexByDay']
BALANCE_SHEET_COLLECTION=GLOBAL_MONGO_CONN[FUNDAMENTAL_DB][BALANCE_SHEET]
PROFIT_SHEET_COLLECTION=GLOBAL_MONGO_CONN[FUNDAMENTAL_DB][PROFIT_SHEET]
CASHFLOW_SHEET_COLLECTION=GLOBAL_MONGO_CONN[FUNDAMENTAL_DB][CASHFLOW_SHEET]
FINANCIAL_INDICATOR_COLLECTION=GLOBAL_MONGO_CONN[FUNDAMENTAL_DB][FINANCIAL_INDICATOR_SHEET]
